services:
  - type: web
    name: franks-candidate-concierge-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: DATABASE_URL
        fromDatabase:
          name: concierge-db
          property: connectionString
      - key: PORT
        value: 8000 