services:
  - type: web
    name: franks-candidate-concierge-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python startup.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true 